### ISSUE TITLE
The event-display image referenced does not work

### ISSUE THREAD

**Issue by RE-codes** [IBM/knative101-eventing#3]
There seems to be a compatibility issue with the image referenced and the current version of knative deployed with `ibmcloud ks cluster addon enable knative -c <cluster>`.

Rather than the expected output, it delivers this in the event-display logs:
```
{"level":"error","ts":1585676940.008811,"logger":"fallback","caller":"http/transport.go:408","msg":"failed to decode message","error":"unknown encoding","stacktrace":"github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/go/src/github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:408\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2375\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878"}
```
After updating the `event-display` service to use `gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:b2c341b2f36c46ed20041364e19cdaa19c7002dad97646f69717257b5afa4512`, the output is as expected.

**Comment by shiliy** [comment]
same issue and similar solution as above. Here is my updated version of `service.yaml` that worked with Knative v1.3 on IKS: 

```

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
```
