### ISSUE TITLE
Needs to upgrade/migrate code to work with Knative v1.3

### ISSUE THREAD

**Issue by shiliy** [IBM/knative101-eventing#4]
`CronJob` has been deprecated in Knative. And an update to `PingSource` as the event source worked for me. Here is my yaml:

```
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: test-ping-source
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: "{\"message\": \"Hello world!\"}"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
```

An updated version of the matching `service.yml` is attached in [this issue](https://github.com/IBM/knative101-eventing/issues/3).
